events {}

http {
    upstream identity {
        server identity-service:3001;
    }
    upstream application {
        server application-service:3002;
    }
    upstream interoperability {
        server interoperability-service:3003;
    }
    upstream notification {
        server notification-service:3004;
    }
    upstream mockgov {
        server mock-government-service:3005;
    }

    server {
        listen 80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-ID $request_id;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        location /api/auth/ {
            proxy_pass http://identity/;
        }
        location /api/applications/ {
            proxy_pass http://application/;
        }
        location /api/interoperability/ {
            proxy_pass http://interoperability/;
        }
        location /api/notifications/ {
            proxy_pass http://notification/;
        }
        location /api/mock/ {
            proxy_pass http://mockgov/;
        }
    }
}
